version: '3'
services:

#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "35432:5432"
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=example
#      - POSTGRES_DB=mails_db
#  mail:
#    container_name: tezos-digisign-mail
#    image: gessnerfl/fake-smtp-server:latest
#    restart: always
#    ports:
#      - "5025:5025"
#      - "5080:5080"
#      - "5081:5081"
#    environment:
#      FAKESMTP_AUTHENTICATION_USERNAME: username
#      FAKESMTP_AUTHENTICATION_PASSWORD: password
#
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=keycloak_db
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
#    volumes:
#      - ./imports:/temp/
#    command:
#      - "-b 0.0.0.0 -Dkeycloak.import=/temp/message-service.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: user
      DB_PASSWORD: example
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
